version: '3.8'


services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: vlab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smp@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=vlab_db
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=smp@123
    depends_on:
      - db

volumes:
  postgres_data:
