# Generated by Django 5.2 on 2025-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=20)),
                ('experiment_class', models.CharField(max_length=10)),
                ('theory_text', models.TextField()),
                ('html_file', models.CharField(max_length=100)),
            ],
        ),
    ]
