"""
Django settings for vlab project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file for local development
load_dotenv()

# --- Core Security Settings ---
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECRET_KEY is loaded from environment variables in production.
# A default is provided for local development, but it should not be used in production.
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-kwrn%)q2rl5obc6g9w4s!0tdwktyb*rjf8c07y@z-d)%x(w$=&")

# DEBUG is False by default for security. Turn it on for local development by setting DEBUG=1 in .env
DEBUG = os.getenv("DEBUG", "0").lower() in ["1", "true"]

# ALLOWED_HOSTS should be configured with your domain in production.
# Using '*' is acceptable for services like Google Cloud Run that provide a proxy.
ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    'https://virtual-lab-715732606815.asia-south1.run.app',
]

# --- Application Definition ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'labs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise middleware should be placed right after the security middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vlab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vlab.wsgi.application'
AUTH_USER_MODEL = 'core.CustomUser'
LOGIN_URL = '/login/'


# --- Database Configuration ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DJANGO_DB_NAME"),
        "USER": os.getenv("DJANGO_DB_USER"),
        "PASSWORD": os.getenv("DJANGO_DB_PASSWORD"),
        "HOST": os.getenv("DJANGO_DB_HOST"),
        "PORT": os.getenv("DJANGO_DB_PORT", "5432"),
        "OPTIONS": {
            # Use 'require' for services like Google Cloud SQL
            "sslmode": os.getenv("DJANGO_DB_SSLMODE", "require"),
        },
    }
}


# --- Password Validation ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- Email Configuration ---
# IMPORTANT: Use environment variables for credentials in production.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')


# --- Internationalization & Time Zones ---
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- Static Files Configuration (for Production) ---
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# http://whitenoise.evans.io/en/stable/django.html

STATIC_URL = '/static/'
# Directory where collectstatic will gather all static files.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Storage engine that compresses files and creates unique names for caching.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Additional locations for static files (optional, but good practice).
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# --- Default Primary Key Field Type ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

